import { RequestHandler, Router } from 'express';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { prisma } from '../../db/prisma';
import { AuthRequest, requireAuth, requirePermission } from '../../middleware/auth';
import { getOrganizationSubscription, getUsageForCurrentPeriod, recordCommercialUsage, SubscriptionNotBillableError, UsageLimitExceededError, usageCategories } from './billing.service';

const router = Router();
const planSchema = z.object({ name: z.string().trim().min(1).max(120), description: z.string().trim().max(1000).optional().nullable(), isActive: z.boolean().optional(), monthlyPrice: z.string().regex(/^\d+(\.\d{1,2})?$/), currency: z.string().trim().length(3).transform((value) => value.toUpperCase()), contactLimit: z.number().int().nonnegative().nullable().optional(), emailLimit: z.number().int().nonnegative().nullable().optional(), smsLimit: z.number().int().nonnegative().nullable().optional(), voiceMinuteLimit: z.number().int().nonnegative().nullable().optional(), phoneNumberLimit: z.number().int().nonnegative().nullable().optional() });
const subscriptionSchema = z.object({ planId: z.string().min(1), status: z.enum(['TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'EXPIRED']).default('TRIALING'), currentPeriodStart: z.string().datetime(), currentPeriodEnd: z.string().datetime(), cancelAtPeriodEnd: z.boolean().optional() });
const usageSchema = z.object({ category: z.enum(usageCategories), quantity: z.number().int().positive(), unit: z.string().trim().min(1).max(40), provider: z.string().trim().min(1).max(80).default('INTERNAL'), sourceType: z.string().trim().max(80).optional(), sourceId: z.string().trim().max(160).optional(), campaignId: z.string().optional(), campaignRecipientId: z.string().optional(), messageId: z.string().optional(), telecomCallId: z.string().optional(), telecomMessageId: z.string().optional(), providerId: z.string().optional(), unitPrice: z.string().regex(/^\d+(\.\d{1,6})?$/).optional(), currency: z.string().trim().length(3).transform((value) => value.toUpperCase()).optional(), idempotencyKey: z.string().trim().min(1).max(200), metadata: z.record(z.unknown()).optional() });
const requireBillingRead: RequestHandler = (req, res, next) => { const user = req.user; if (!user) return res.status(401).json({ message: 'Authentication required' }); if (user.role === 'OWNER' || user.role === 'ADMIN' || user.permissions.includes('reports.read') || user.permissions.includes('billing.manage')) return next(); return res.status(403).json({ message: 'Forbidden: missing billing read permission' }); };

router.get('/plans', requireAuth, requirePermission('billing.manage'), async (_req, res) => res.json({ data: await prisma.plan.findMany({ orderBy: { createdAt: 'desc' } }) }));
router.get('/plans/:id', requireAuth, requirePermission('billing.manage'), async (req, res) => { const plan = await prisma.plan.findUnique({ where: { id: req.params.id } }); return plan ? res.json({ data: plan }) : res.status(404).json({ message: 'Plan not found' }); });
router.post('/plans', requireAuth, requirePermission('billing.manage'), async (req, res) => { const parsed = planSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Validation failed', issues: parsed.error.issues }); const { monthlyPrice, ...rest } = parsed.data; return res.status(201).json({ data: await prisma.plan.create({ data: { ...rest, monthlyPrice: new Prisma.Decimal(monthlyPrice) } }) }); });
router.patch('/plans/:id', requireAuth, requirePermission('billing.manage'), async (req, res) => { const parsed = planSchema.partial().safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Validation failed', issues: parsed.error.issues }); const existing = await prisma.plan.findUnique({ where: { id: req.params.id } }); if (!existing) return res.status(404).json({ message: 'Plan not found' }); const { monthlyPrice, ...rest } = parsed.data; return res.json({ data: await prisma.plan.update({ where: { id: existing.id }, data: { ...rest, ...(monthlyPrice === undefined ? {} : { monthlyPrice: new Prisma.Decimal(monthlyPrice) }) } }) }); });
router.get('/subscription', requireAuth, requireBillingRead, async (req: AuthRequest, res) => res.json({ data: await getOrganizationSubscription(req.user!.organizationId) }));
router.put('/subscription', requireAuth, requirePermission('billing.manage'), async (req: AuthRequest, res) => { const parsed = subscriptionSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Validation failed', issues: parsed.error.issues }); const plan = await prisma.plan.findFirst({ where: { id: parsed.data.planId, isActive: true } }); if (!plan) return res.status(400).json({ message: 'Active plan not found' }); const data = { planId: parsed.data.planId, status: parsed.data.status, currentPeriodStart: new Date(parsed.data.currentPeriodStart), currentPeriodEnd: new Date(parsed.data.currentPeriodEnd), cancelAtPeriodEnd: parsed.data.cancelAtPeriodEnd ?? false }; return res.json({ data: await prisma.subscription.upsert({ where: { organizationId: req.user!.organizationId }, create: { organizationId: req.user!.organizationId, ...data }, update: data, include: { plan: true } }) }); });
router.get('/usage', requireAuth, requireBillingRead, async (req: AuthRequest, res) => res.json({ data: await getUsageForCurrentPeriod(req.user!.organizationId) }));
router.post('/usage', requireAuth, requirePermission('billing.manage'), async (req: AuthRequest, res) => { const parsed = usageSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Validation failed', issues: parsed.error.issues }); try { const result = await recordCommercialUsage(req.user!.organizationId, parsed.data); return res.status(result.duplicate ? 200 : 201).json({ data: result.record, duplicate: result.duplicate }); } catch (error) { if (error instanceof UsageLimitExceededError) return res.status(409).json({ code: error.code, message: error.message, category: error.category, currentUsage: error.used, requestedQuantity: error.requested, planLimit: error.limit, remaining: error.remaining }); if (error instanceof SubscriptionNotBillableError) return res.status(409).json({ code: error.status === 'MISSING' ? 'SUBSCRIPTION_REQUIRED' : error.code, message: error.status === 'MISSING' ? 'Organization has no subscription' : error.message, status: error.status }); throw error; } });

export default router;
